import fs from "fs";
import path from "path";

export interface QueryPerformance {
  query: string;
  createdAt: string;
  totalAttempts: number;
  validBillboardsFound: number;
  successRate: number; // validBillboardsFound / totalAttempts
  lastUsed: string;
  avgConfidence: number; // Average OpenAI confidence score
  source: "initial" | "claude-generated" | "manual";
}

interface QueryStore {
  queries: QueryPerformance[];
  dailyGoal: number;
  lastUpdated: string;
}

const QUERY_PATH = path.join(process.cwd(), "data", "query-performance.json");

const INITIAL_QUERIES: Omit<QueryPerformance, "totalAttempts" | "validBillboardsFound" | "successRate" | "lastUsed" | "avgConfidence">[] = [
  {
    query: '("just dropped" OR "launched" OR "our billboard") SF has:images -is:retweet -is:reply',
    createdAt: new Date().toISOString(),
    source: "initial",
  },
  {
    query: '("new billboard" OR "billboard in SF" OR "billboard in San Francisco") has:images -is:retweet',
    createdAt: new Date().toISOString(),
    source: "initial",
  },
  {
    query: '(from:numeralhq OR from:stripe OR from:vercel OR from:anthropicai OR from:openai) billboard has:images',
    createdAt: new Date().toISOString(),
    source: "initial",
  },
  {
    query: '("South Park" OR Mission OR SOMA OR "Highway 101") billboard SF has:images',
    createdAt: new Date().toISOString(),
    source: "initial",
  },
  {
    query: '(startup OR tech OR "YC") "billboard" SF has:images -is:retweet',
    createdAt: new Date().toISOString(),
    source: "initial",
  },
];

function ensureQueryFile(): QueryStore {
  const dir = path.dirname(QUERY_PATH);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  if (!fs.existsSync(QUERY_PATH)) {
    const initial: QueryStore = {
      queries: INITIAL_QUERIES.map(q => ({
        ...q,
        totalAttempts: 0,
        validBillboardsFound: 0,
        successRate: 0,
        lastUsed: new Date().toISOString(),
        avgConfidence: 0,
      })),
      dailyGoal: 3,
      lastUpdated: new Date().toISOString(),
    };
    fs.writeFileSync(QUERY_PATH, JSON.stringify(initial, null, 2));
    return initial;
  }
  return JSON.parse(fs.readFileSync(QUERY_PATH, "utf-8")) as QueryStore;
}

function saveQueryStore(store: QueryStore): void {
  const dir = path.dirname(QUERY_PATH);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  store.lastUpdated = new Date().toISOString();
  fs.writeFileSync(QUERY_PATH, JSON.stringify(store, null, 2));
}

export function recordQueryResult(
  query: string,
  validBillboardsFound: number,
  avgConfidence: number,
): void {
  const store = ensureQueryFile();

  let queryPerf = store.queries.find((q) => q.query === query);

  if (!queryPerf) {
    // New query (probably generated by Claude)
    queryPerf = {
      query,
      createdAt: new Date().toISOString(),
      totalAttempts: 0,
      validBillboardsFound: 0,
      successRate: 0,
      lastUsed: new Date().toISOString(),
      avgConfidence: 0,
      source: "claude-generated",
    };
    store.queries.push(queryPerf);
  }

  // Update stats
  queryPerf.totalAttempts += 1;
  queryPerf.validBillboardsFound += validBillboardsFound;
  queryPerf.successRate = queryPerf.validBillboardsFound / queryPerf.totalAttempts;
  queryPerf.lastUsed = new Date().toISOString();

  // Update average confidence (weighted average)
  const totalWeight = queryPerf.totalAttempts;
  queryPerf.avgConfidence =
    (queryPerf.avgConfidence * (totalWeight - 1) + avgConfidence) / totalWeight;

  saveQueryStore(store);

  console.log(
    `[Query Performance] ${query.substring(0, 50)}... → ${validBillboardsFound} valid (success rate: ${(queryPerf.successRate * 100).toFixed(1)}%)`,
  );
}

export function getTopPerformingQueries(limit = 5): QueryPerformance[] {
  const store = ensureQueryFile();
  return store.queries
    .sort((a, b) => {
      // Sort by success rate, then by avg confidence, then by recency
      if (b.successRate !== a.successRate) {
        return b.successRate - a.successRate;
      }
      if (b.avgConfidence !== a.avgConfidence) {
        return b.avgConfidence - a.avgConfidence;
      }
      return new Date(b.lastUsed).getTime() - new Date(a.lastUsed).getTime();
    })
    .slice(0, limit);
}

export function getAllQueries(): QueryPerformance[] {
  const store = ensureQueryFile();
  return store.queries;
}

export function addNewQuery(query: string, source: "claude-generated" | "manual" = "manual"): void {
  const store = ensureQueryFile();

  // Check if query already exists
  if (store.queries.some((q) => q.query === query)) {
    console.log(`[Query Performance] Query already exists: ${query.substring(0, 50)}...`);
    return;
  }

  store.queries.push({
    query,
    createdAt: new Date().toISOString(),
    totalAttempts: 0,
    validBillboardsFound: 0,
    successRate: 0,
    lastUsed: new Date().toISOString(),
    avgConfidence: 0,
    source,
  });

  saveQueryStore(store);
  console.log(`[Query Performance] Added new query: ${query.substring(0, 50)}...`);
}

export function pruneUnderperformingQueries(): void {
  const store = ensureQueryFile();

  // Remove queries that have been tried 5+ times but have 0% success rate
  const before = store.queries.length;
  store.queries = store.queries.filter((q) => {
    if (q.totalAttempts >= 5 && q.successRate === 0) {
      console.log(`[Query Performance] Pruning underperforming query: ${q.query.substring(0, 50)}...`);
      return false;
    }
    return true;
  });

  const pruned = before - store.queries.length;
  if (pruned > 0) {
    saveQueryStore(store);
    console.log(`[Query Performance] Pruned ${pruned} underperforming queries`);
  }
}

export function getQueryStats() {
  const store = ensureQueryFile();
  const totalQueries = store.queries.length;
  const testedQueries = store.queries.filter((q) => q.totalAttempts > 0).length;
  const successfulQueries = store.queries.filter((q) => q.validBillboardsFound > 0).length;

  const topQueries = getTopPerformingQueries(10);

  return {
    totalQueries,
    testedQueries,
    successfulQueries,
    dailyGoal: store.dailyGoal,
    topQueries,
  };
}
